require("plugins/yazi")
require("plugins/which-key")
require("plugins/telescope")
require("plugins/hlslens")
require("plugins/completion")
require("plugins/conform") -- code formatter, could use LSP formatting instead if you prefer
require("plugins/tiny-inline-diagnostic")
require("plugins/ai")
require("plugins/markview")
require("plugins/avante")
require("plugins/opencode")
require("plugins/dashboard")
require("plugins/flash")
require("plugins/snacks")
require("plugins/grug-far")
require("plugins/otter") -- LSP for Lua/bash embedded in Nix strings
-- require("plugins/treesitter-textobjects")
