require("plugins/yazi")
require("plugins/which-key")
require("plugins/telescope")
require("plugins/completion")
require("plugins/conform") -- code formatter, could use LSP formatting instead if you prefer
require("plugins/ai")
require("plugins/markview")
require("plugins/opencode")
require("plugins/dashboard")
require("plugins/flash")
require("plugins/snacks")
require("plugins/grug-far")
-- require("plugins/treesitter-textobjects")
