# convenient shell functions

# quick navigation to git repo root
function cdroot() {
    local root
    root=$(git rev-parse --show-toplevel 2>/dev/null)
    if [ $? -eq 0 ]; then
        cd "$root" || exit
    else
        echo "Not in a git repository"
        return 1
    fi
}

# `y` yazi wrapper (cd-on-quit) auto-generated by programs.yazi
# (enableZshIntegration + shellWrapperName, default "y" at stateVersion >= 26.05)

# nix-shell-init: scaffold a per-project dev shell.
# Writes flake.nix (nixpkgs-unstable + git-hooks; node/pnpm/just devShell; a
# personal-identity pre-push guard) and a `use flake` .envrc, stages them (Nix
# flakes ignore files git does not track), then runs `direnv allow`.
# Template mirrors ~/Documents/KangaFlow/flake.nix minus its project-only hooks.
function nix-shell-init() {
    if [ -e flake.nix ]; then
        echo "nix-shell-init: flake.nix already exists — refusing to overwrite" >&2
        return 1
    fi

    cat > flake.nix <<'NIX_FLAKE_TEMPLATE'
{
  description = "dev shell";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    # Externally extensible system list. It has no inputs of its own, so it
    # takes no `inputs.nixpkgs.follows` override (that would just warn).
    systems.url = "github:nix-systems/default";

    git-hooks = {
      url = "github:cachix/git-hooks.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      systems,
      ...
    }@inputs:
    let
      forEachSystem =
        f: nixpkgs.lib.genAttrs (import systems) (system: f system nixpkgs.legacyPackages.${system});
    in
    {
      checks = forEachSystem (
        system: pkgs: {
          pre-commit-check = inputs.git-hooks.lib.${system}.run {
            src = ./.;
            hooks = {
              # Nix hygiene.
              nixfmt.enable = true;
              statix.enable = true;
              deadnix.enable = true;

              # Optional: project-pinned linter/formatter. Uncomment and point at
              # the binary in node_modules so the hook, CI, and editor all run the
              # exact same version. Swap for prettier/eslint/ruff/etc. as needed.
              # biome = {
              #   enable = true;
              #   settings.binPath = "./node_modules/.bin/biome";
              # };

              # Pre-push guard: reject any incoming commit whose author OR
              # committer is not the personal identity. Keeps work identity out
              # of this repo's history for good.
              check-author = {
                enable = true;
                name = "check git author";
                entry = "${pkgs.writeShellScriptBin "check-author" ''
                  expected="samuelyongw@gmail.com"
                  zero="0000000000000000000000000000000000000000"
                  while IFS=' ' read -r _local_ref local_sha _remote_ref remote_sha; do
                    # Skip branch deletions.
                    [ "$local_sha" = "$zero" ] && continue

                    # Isolate only the new incoming commits.
                    if [ "$remote_sha" = "$zero" ]; then
                      commits=$(git rev-list "$local_sha" --not --remotes 2>/dev/null)
                    else
                      commits=$(git rev-list "$remote_sha..$local_sha" 2>/dev/null)
                    fi

                    [ -z "$commits" ] && continue

                    while IFS= read -r commit; do
                      IFS='|' read -r author_email committer_email <<< "$(git log -1 --format="%ae|%ce" "$commit" 2>/dev/null)"

                      if [ "$author_email" != "$expected" ]; then
                        echo "Push rejected: $commit not authored by <$expected> (got: $author_email)"
                        exit 1
                      fi
                      if [ "$committer_email" != "$expected" ]; then
                        echo "Push rejected: $commit not committed by <$expected> (got: $committer_email)"
                        exit 1
                      fi
                    done <<< "$commits"
                  done
                ''}/bin/check-author";
                language = "system";
                pass_filenames = false;
                always_run = true;
                stages = [ "pre-push" ];
              };
            };
          };
        }
      );

      devShells = forEachSystem (
        system: pkgs: {
          default = pkgs.mkShell {
            # shellHook = installs the git pre-commit hook defined above.
            inherit (self.checks.${system}.pre-commit-check) shellHook;

            # Suggested project tools live in this comment so the default shell
            # stays minimal AND statix-clean (an empty `[ ] ++ ...` is a lint error).
            # Add what the project needs by prepending a list, e.g.:
            #   packages = with pkgs; [ nodejs_26 pnpm just python3 uv rustup go ]
            #     ++ self.checks.${system}.pre-commit-check.enabledPackages;
            packages = self.checks.${system}.pre-commit-check.enabledPackages;
          };
        }
      );
    };
}
NIX_FLAKE_TEMPLATE

    [ -e .envrc ] || printf 'use flake\n' > .envrc

    # Nix flakes only see git-tracked files; stage so `nix develop`/direnv resolve them.
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        git add flake.nix .envrc 2>/dev/null
    fi

    command -v direnv >/dev/null 2>&1 && direnv allow

    echo "nix-shell-init: created flake.nix + .envrc"
}

